name: Deployment Metrics
description: |
  Various steps for publishing deployment metrics, such as deployment frequency, lead time, and MTTR.
  This requires organisational level secrets, such as DATADOG_API_KEY 

inputs:
  app_name:
    description: The name of the app being deployed.
    required: true
  app_version:
    description: The version of the app being deployed.
    required: true
  deployment_start_date:
    description: The start date of the deployment in ISO 8601 format.
    required: true
  deployment_end_date:
    description: The end date of the deployment in ISO 8601 format.
    required: true
  deployment_env:
    description: The environment the app is being deployed to.
    required: true 
  dd_api_key:
    description: The Datadog API key.
    required: true
  sha:
    description: The git sha of the commit being deployed.
    required: true
  repository:
    description: The git repository being deployed.
    required: true


runs:
  using: composite
  steps:

    - name: deployment frequency
      id: deployment-frequency
      shell: bash

      run: |
        echo "app_name: ${{inputs.app_name}}"
        echo "app_version: ${{inputs.app_version}}"
        echo "deployment_start_date: ${{inputs.deployment_start_date}}"
        echo "deployment_end_date: ${{inputs.deployment_end_date}}"
        echo "deployment_env: ${{inputs.deployment_env}}"
        echo "dd_api_key: ${{inputs.dd_api_key}}"
        echo "sha: ${{inputs.sha}}"
        echo "repository: ${{inputs.repository}}"
      
        curl -X POST "https://api.datadoghq.eu/api/v2/dora/deployment" \
        -H "Accept: application/json" \
        -H "Content-Type: application/json" \
        -H "DD-API-KEY: ${{inputs.dd_api_key}}" \
        -d @- << EOF
        {
          "data": {
            "attributes": {
              "service": "${{inputs.app_name}}",
              "version": "${{inputs.app_version}}",
              "started_at": "${{inputs.deployment_start_date}}",
              "finished_at": "${{inputs.deployment_end_date}}",
              "git": {
                "commit_sha": "${{inputs.sha}}",
                "repository_url": "${{inputs.repository}}"
              },
              "env": "${{inputs.deployment_env}}"
            }
          }
        }
        EOF
        