name: Deployment Metrics
description: |
  Various steps for publishing deployment metrics, such as deployment frequency, lead time, and MTTR.
  This requires organisational level secrets, such as DATADOG_API_KEY 

inputs:
  app-name:
    description: The name of the app being deployed.
    required: true
  app-version:
    description: The version of the app being deployed.
    required: true
  deployment-start-date:
    description: The start date of the deployment in ISO 8601 format.
    required: true
  deployment-end-date:
    description: The end date of the deployment in ISO 8601 format.
    required: true
  env:
    description: The environment the app is being deployed to.
    required: true 
env:
    DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    APP_NAME: ${{ inputs.app-name }}
    APP_VERSION: ${{ inputs.app-version }}
    DEPLOYMENT_START_DATE: ${{ inputs.deployment-start-date }}
    DEPLOYMENT_END_DATE: ${{ inputs.deployment-end-date }}
    DEPLOY_ENV: ${{ inputs.env }}
    GIT_SHA: ${{ github.sha }}
    GIT_REPOSITORY: ${{ github.repository }}

runs:
  using: composite
  steps:
    - name: deployment frequency
      id: deployment-frequency
      shell: bash
      run: |
        export DD_SITE="datadoghq.eu"
        echo "Inputs:"
        echo "  app-name: ${{ inputs.app-name }}"
        echo "  app-version: ${{ inputs.app-version }}"
        echo "  deployment-start-date: ${{ inputs.deployment-start-date }}"
        echo "  deployment-end-date: ${{ inputs.deployment-end-date }}"
        echo "  env: ${{ inputs.env }}"
        echo ""
        echo "Environment Variables:"
        echo "  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}"
        echo "  APP_NAME: ${{ inputs.app-name }}"
        echo "  APP_VERSION: ${{ inputs.app-version }}"
        echo "  DEPLOYMENT_START_DATE: ${{ inputs.deployment-start-date }}"
        echo "  DEPLOYMENT_END_DATE: ${{ inputs.deployment-end-date }}"
        echo "  ENV: ${{ inputs.env }}"
        echo "  GIT_SHA: ${{ github.sha }}"
        echo "  GIT_REPOSITORY: ${{ github.repository }}"
        
        
        curl -X POST "https://api.${DD_SITE}/api/v2/dora/deployment" \
        -H "Accept: application/json" \
        -H "Content-Type: application/json" \
        -H "DD-API-KEY: ${DD_API_KEY}" \
        -d @- << EOF
        {
          "data": {
            "attributes": {
              "service": "${APP_NAME}",
              "version": "${APP_VERSION}",
              "started_at": "${DEPLOYMENT_START_DATE}",
              "finished_at": "${DEPLOYMENT_END_DATE}",
              "git": {
                "commit_sha": "${GIT_SHA}",
                "repository_url": "${GIT_REPOSITORY}"
              },
              "env": "${DEPLOY_ENV}"
            }
          }
        }
        EOF
        