name: Deployment Metrics
description: |
  Various steps for publishing deployment metrics, such as deployment frequency, lead time, and MTTR.
  This requires organisational level secrets, such as DATADOG_API_KEY 

inputs:
  app_name:
    description: The name of the app being deployed.
    required: true
  app_version:
    description: The version of the app being deployed.
    required: true
  deployment_start_date:
    description: The start date of the deployment in ISO 8601 format.
    required: true
  deployment_end_date:
    description: The end date of the deployment in ISO 8601 format.
    required: true
  deployment_env:
    description: The environment the app is being deployed to.
    required: true 
  dd_api_ßkey:
    description: The Datadog API key.
    required: true
  sha:
    description: The git sha of the commit being deployed.
    required: true
  repository:
    description: The git repository being deployed.
    required: true


runs:
  using: composite
  steps:

    - name: deployment frequency
      id: deployment-frequency
      shell: bash
      run: |
        export dd_site="datadoghq.eu"
        echo "DATADOG_API_KEY: $dd_api_key"
        echo "APP_NAME: $app_name"
        echo "APP_VERSION: $app_version"
        echo "DEPLOYMENT_START_DATE: $deployment_start_date"
        echo "DEPLOYMENT_END_DATE: $deployment_end_date"
        echo "DEPLOYMENT_ENV: $deployment_env"
        echo "GIT_SHA: $sha"
        echo "GIT_REPOSITORY: $repository"
       
        curl -X POST "https://api.${dd_site}/api/v2/dora/deployment" \
        -H "Accept: application/json" \
        -H "Content-Type: application/json" \
        -H "DD-API-KEY: ${dd_api_key}" \
        -d @- << EOF
        {
          "data": {
            "attributes": {
              "service": "${app_name}",
              "version": "${app_version}",
              "started_at": "${deployment_start_date}",
              "finished_at": "${deployment_end_date}",
              "git": {
                "commit_sha": "${sha}",
                "repository_url": "${git_repository}"
              },
              "env": "${deployment_env}"
            }
          }
        }
        EOF
        